# Use the official Debian base image with a specific tag
FROM debian:trixie-slim

# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# Update the package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl 
# Additional steps to customize your image
#RUN apt-get install
#
# Set the default command to run when the container starts
CMD ["/bin/bash"]